### ISSUE TITLE
What changes are needed to support box size of more than 16x16 ?

### ISSUE THREAD

**Issue by option-greek** [AlexGhiondea/SudokuSolver#14]
Hi,
What changes are needed to support box size of more than 16x16  (I see that this limit is hard coded). I'm trying to modify this to support NxN.

Regards,
OG

**Comment by option-greek** [comment]
Aah. Now I get it. It is for representation on the grid in hex :). I wonder what I can use for representing it on the grid for 6x6.

**Comment by AlexGhiondea** [comment]
You should be able to use another visualization for it -- regular characters perhaps?

**Comment by AlexGhiondea** [comment]
I remember why there is a limit.

If you have a 5x5 box then you are going to have a 25x25 Sudoku grid. This is the max you can represent with ASCII characters. 

You can make the board larger, but be aware of two things:
- The larger the board, the longer it will take to create and solve it.
- You need to figure out a better way to representing nodes than ASCII characters.

If you want an NxN grid then you can probably change the way the values are displayed... shouldn't be too much work... but you will probably lose the ability to parse the puzzles from a file.

Let me know if you end up going down this path!

**Comment by AlexGhiondea** [comment]
Closing now -- please reactivate if you need help!
